-- Query1: Calculate the total course purchase value for each student using CTE --
WITH student_spending AS (
    SELECT
        s.student_id,
        s.full_name,
        SUM(c.price) AS total_value
    FROM students s
    JOIN enrollments e ON s.student_id = e.student_id
    JOIN courses c ON e.course_id = c.course_id
    GROUP BY s.student_id, s.full_name
)
SELECT * FROM student_spending;

-- Query2: Find students whose total course value is higher than the average student value using CTE --
WITH student_spending AS (
    SELECT
        s.student_id,
        s.full_name,
        SUM(c.price) AS total_value
    FROM students s
    JOIN enrollments e ON s.student_id = e.student_id
    JOIN courses c ON e.course_id = c.course_id
    GROUP BY s.student_id, s.full_name
)
SELECT *
FROM student_spending
WHERE total_value > (SELECT AVG(total_value) FROM student_spending);
 
-- Query3: Rank students based on their total course spending from highest to lowest --
SELECT
    student_id,
    full_name,
    total_value,
    RANK() OVER (ORDER BY total_value DESC) AS spending_rank
FROM (
    SELECT
        s.student_id,
        s.full_name,
        SUM(c.price) AS total_value
    FROM students s
    JOIN enrollments e ON s.student_id = e.student_id
    JOIN courses c ON e.course_id = c.course_id
    GROUP BY s.student_id, s.full_name
) x;

-- Query4: Identify the top 10% highest-value students based on course spending --
SELECT *
FROM (
    SELECT
        s.student_id,
        s.full_name,
        SUM(c.price) AS total_value,
        NTILE(10) OVER (ORDER BY SUM(c.price) DESC) AS tile
    FROM students s
    JOIN enrollments e ON s.student_id = e.student_id
    JOIN courses c ON e.course_id = c.course_id
    GROUP BY s.student_id, s.full_name
) x
WHERE tile = 1;

-- Query5: Calculate total revenue generated by each course --
SELECT
    c.course_id,
    c.course_name,
    SUM(c.price) AS total_revenue
FROM courses c
JOIN enrollments e ON c.course_id = e.course_id
GROUP BY c.course_id, c.course_name;

-- Query6: Identify students who never progressed beyond 20% in any enrolled course --
SELECT
    s.student_id,
    s.full_name
FROM students s
JOIN enrollments e ON s.student_id = e.student_id
JOIN course_progress cp ON e.enrollment_id = cp.enrollment_id
GROUP BY s.student_id, s.full_name
HAVING MAX(cp.completed_percent) <= 20;

-- Query7: Find courses with the highest average completion percentage --
SELECT
    c.course_id,
    c.course_name,
    ROUND(AVG(cp.completed_percent), 2) AS avg_completion
FROM courses c
JOIN enrollments e ON c.course_id = e.course_id
JOIN course_progress cp ON e.enrollment_id = cp.enrollment_id
GROUP BY c.course_id, c.course_name
ORDER BY avg_completion DESC;

-- Query8: Classify students into High,Moderate,and Low engagement based on average completion --
SELECT
    s.student_id,
    s.full_name,
    CASE
        WHEN AVG(cp.completed_percent) >= 70 THEN 'High'
        WHEN AVG(cp.completed_percent) BETWEEN 30 AND 69 THEN 'Moderate'
        ELSE 'Low'
    END AS engagement_level
FROM students s
JOIN enrollments e ON s.student_id = e.student_id
JOIN course_progress cp ON e.enrollment_id = cp.enrollment_id
GROUP BY s.student_id, s.full_name;

-- Query9: Find students who enrolled in courses but never started progress --
SELECT
    s.student_id,
    s.full_name
FROM students s
JOIN enrollments e ON s.student_id = e.student_id
JOIN course_progress cp ON e.enrollment_id = cp.enrollment_id
GROUP BY s.student_id, s.full_name
HAVING MAX(cp.completed_percent) = 0;

-- Query10: Show month-wise enrollments count and compare with the previous month --
SELECT
    month,
    total_enrollments,
    LAG(total_enrollments) OVER (ORDER BY month) AS previous_month
FROM (
    SELECT
        DATE_FORMAT(enrollment_date, '%Y-%m') AS month,
        COUNT(*) AS total_enrollments
    FROM enrollments
    GROUP BY month
) x;

-- Query11: Calculate month-over-month enrollments growth percentage --
SELECT
    month,
    enrollments,
    ROUND(
        (enrollments - LAG(enrollments) OVER (ORDER BY month))
        / LAG(enrollments) OVER (ORDER BY month) * 100, 2
    ) AS month_growth_pct
FROM (
    SELECT
        DATE_FORMAT(enrollment_date, '%Y-%m') AS month,
        COUNT(*) AS enrollments
    FROM enrollments
    GROUP BY month
) x;

-- Query12: Identify students whose course completion improved over time --
SELECT DISTINCT student_id, full_name
FROM (
    SELECT
        s.student_id,
        s.full_name,
        cp.completed_percent,
        LAG(cp.completed_percent)
            OVER (PARTITION BY s.student_id ORDER BY e.enrollment_date) AS prev_completion
    FROM students s
    JOIN enrollments e ON s.student_id = e.student_id
    JOIN course_progress cp ON e.enrollment_id = cp.enrollment_id
) x
WHERE completed_percent > prev_completion;

-- Query13: Find courses with high enrollments but low average completion rates --
SELECT
    c.course_id,
    c.course_name,
    COUNT(e.enrollment_id) AS enrollments,
    AVG(cp.completed_percent) AS avg_completion
FROM courses c
JOIN enrollments e ON c.course_id = e.course_id
JOIN course_progress cp ON e.enrollment_id = cp.enrollment_id
GROUP BY c.course_id, c.course_name
HAVING enrollments > (SELECT AVG(cnt) FROM (
    SELECT COUNT(*) AS cnt FROM enrollments GROUP BY course_id
) x)
AND AVG(cp.completed_percent) < 40;

-- Query14: Create a funnel showing enrolled,active,and completed learners --
SELECT 'Enrolled' AS stage, COUNT(DISTINCT student_id) FROM enrollments
UNION ALL
SELECT 'Active', COUNT(DISTINCT e.student_id)
FROM enrollments e
JOIN course_progress cp ON e.enrollment_id = cp.enrollment_id
WHERE cp.completed_percent > 0
UNION ALL
SELECT 'Completed', COUNT(DISTINCT e.student_id)
FROM enrollments e
JOIN course_progress cp ON e.enrollment_id = cp.enrollment_id
WHERE cp.completed_percent = 100;


-- Query15: Identify students enrolled in more than one course --
SELECT
    s.student_id,
    s.full_name
FROM students s
JOIN enrollments e ON s.student_id = e.student_id
GROUP BY s.student_id, s.full_name
HAVING COUNT(DISTINCT e.course_id) > 1;

-- Query16: Find students contributing to the top 80% of total platform revenue -- 
WITH revenue_rank AS (
    SELECT
        s.student_id,
        s.full_name,
        SUM(c.price) AS total_value,
        SUM(SUM(c.price)) OVER () AS total_revenue,
        SUM(SUM(c.price)) OVER (ORDER BY SUM(c.price) DESC) AS running_total
    FROM students s
    JOIN enrollments e ON s.student_id = e.student_id
    JOIN courses c ON e.course_id = c.course_id
    GROUP BY s.student_id, s.full_name
)
SELECT *
FROM revenue_rank
WHERE running_total <= 0.8 * total_revenue;

-- Query17: Idnetify months with the highest enrolled activity --
SELECT
    DATE_FORMAT(enrollment_date, '%Y-%m') AS month,
    COUNT(*) AS enrollments
FROM enrollments
GROUP BY month
ORDER BY enrollments DESC;

-- Query18: Find students whose course engagement is declining over time --
SELECT DISTINCT student_id, full_name
FROM (
    SELECT
        s.student_id,
        s.full_name,
        cp.completed_percent,
        LAG(cp.completed_percent)
            OVER (PARTITION BY s.student_id ORDER BY e.enrollment_date) AS prev_completion
    FROM students s
    JOIN enrollments e ON s.student_id = e.student_id
    JOIN course_progress cp ON e.enrollment_id = cp.enrollment_id
) x
WHERE completed_percent < prev_completion;

-- Query19: Identify courses that bring the most new students on signup day --
SELECT
    c.course_name,
    COUNT(*) AS same_day_enrollments
FROM enrollments e
JOIN students s ON e.student_id = s.student_id
JOIN courses c ON e.course_id = c.course_id
WHERE e.enrollment_date = s.signup_date
GROUP BY c.course_name
ORDER BY same_day_enrollments DESC;

-- Query20: Generate a platform-level summary showing student count,activity,and learning health --
SELECT
    (SELECT COUNT(*) FROM students) AS total_students,
    (SELECT COUNT(DISTINCT student_id) FROM enrollments) AS active_students,
    (SELECT ROUND(AVG(completed_percent), 2) FROM course_progress) AS avg_completion,
    (SELECT SUM(price) FROM courses c JOIN enrollments e ON c.course_id = e.course_id) AS total_revenue;
